FROM jenkins/agent:bookworm-jdk17

# USER jenkins

USER root

# Install unzip package
RUN apt-get update && apt-get install -y unzip && apt-get clean

COPY ../../jenkins-agent /usr/local/bin/jenkins-agent
RUN chmod +x /usr/local/bin/jenkins-agent &&\
    ln -s /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-slave
# USER ${user}


USER jenkins

ENTRYPOINT ["/usr/local/bin/jenkins-agent"]